version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mqtt
    depends_on:
      - mqtt
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMWUxMDU0YzdhOWJkYWJlYjVkY2ZhYTc4Y2M0YzgxZTgiLCJ0IjoiYmY5YmE0NDgtYmQyMi00ZDg1LWE4ZDAtZTc2MjhjMTIzNTA4IiwicyI6Ik9ERmlOamt6TVRJdE9ESTROeTAwWldRd0xXRXpPRE10TWpObU1EVXhaVGd4WWpkayJ9
